version: '3.8'
services:
  dev-db_chat-server:
    image: postgres:13
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB_NAME: nest
    networks:
      - chat-server
networks:
  chat-server:
